title: "Columbia Qiskit Fall Fest 2025"
description: "Qiskit workshops, hackathons, and talks at Columbia University — Fall 2025"
theme: minima
url: "https://QuantumMeow.github.io"
baseurl: "/columbia-qiskit-fall-fest-2025"
